language: node_js
node_js:
  - "6"
matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
install:
  - npm install -g npm -u
  - npm --version
  - npm install -g codecov jasmine istanbul
  - npm install
script:
  - $(npm bin)/jshint . --verbose
  - $(npm bin)/eslint .
  - export JASMINE_CONFIG_PATH=tests/unit/.jasmine.json && $(npm bin)/babel-node $(npm bin)/istanbul cover $(npm bin)/babel-node $(npm bin)/jasmine
  - $(npm bin)/babel-node $(npm bin)/codecov
