language: node_js
node_js:
  - "6"

install:
- npm install -g codecov jasmine istanbul
script:
- jshint . --verbose
- eslint .
- export JASMINE_CONFIG_PATH=tests/unit/.jasmine.json && istanbul cover jasmine
- codecov
