install:
- npm install -g codecov jasmine
script:
- JASMINE_CONFIG_PATH=tests/unit/.jasmine.json istanbul cover jasmine-node --captureExceptions
  tests/unit
- "codecov"
env:
  CODECOV_TOKEN:
    secure: A0AQfmyP0JckjXQrqyr2pwNwTtnfccg/cKR/3jswulqNSsxVyyvBRYI5SLmAUS1izBn4gpPEiHF4rbcJuZgUMqGmbHmLSfeXY6brz5ylz5/WiMpIDjZEEJlBK9LAAHXk/A5umVO3+OEX535RnboKv72pGgAcBCehJ8TJWwudOvCG3b8Z5MI8W5XKZBIhJ2LqbL7lvazvhqLEjYqYpMBLcFVo9QQru+6BbyVFVFQuKaGUBVbKs++ugvQg1ZJ0Ma4g1YuA5nH69w1weKh3/J1pcKYmzn1ufoTYgnGYB4usB3LrQjopZJJ4v+xJ3NKit4NsO5fnM1OVTpv0AiVeUT50jFkLlQjsZF4l/6Ncd1qWVMGqEfzW4ugzY1bhP7JNICzyr8QcAnsu1fHBYZihRJqKNZol94dKk3IVAo5kl+4xdFB8VLsLUReGcdQdvnAv4EzFgCOGNSJ/IQRxssYQjcc4NIQdiyx43R5d5X78MEllrJGbk7fIYbiwDHuJ4ebRKNMHH4XW5khA802DW/fmDAuM2opFA8UMZ0G+NErNLhhGgdN0HIq8W4BnVobiOpwOTieiKB048dNM9h5OcEnIFTOBOiGfpZ6OkrudH9jNQGdDXH/BxvcY6V56ZsHkNR/gKH0Xp1KBDSnFBSApfHYufpjPw5qITVjlqJQAnl5srSr2ff4=
