'use strict';
// http://reprap.org/wiki/G-code
// http://marlinfw.org/docs/gcode/G033.html
module.exports = {
	STOP: "M0",
	EMERGENCY_STOP: "M112",
	SLEEP: "M1",
	PROGRAM_END: "M2",
	TOOL_CHANGE: "M6",
	ENABLE_ALL_STEPPERS: "M17",
	DISABLE_ALL_STEPPERS: "M18",

	// MAKERBOT: M70
	DISPLAY_MESSAGE: "M117",
	ATX_POWER_ON: "M80",
	ATX_POWER_OFF: "M81",

	SET_EXTRUDER_TEMP: "M104",
	GET_EXTRUDER_TEMP: "M105",
	SET_EXTRUDER_TEMP_AND_WAIT: "M109",

	FAN_ON: "M106",
	FAN_OFF: "M107",

	CANCEL_HEATING: "M108",

	SET_CURRENT_LINENUMBER: "M110",
	SET_DEBUG_LEVEL: "M111",

	SET_EXTRUDER_PWM: "M113",

	GET_CURRENT_POSITION: "M114",
	GET_FIRMWARE_VERSION: "M115",

	WAIT: "M116",

	NEGOTIATE_FEATURES: "M118",
	GET_ENDSTOP_STATUS: "M119",

	ENABLE_ENDSTOP_DETECTION: "M120",
	DISABLE_ENDSTOP_DETECTION: "M121",

	DIAGNOSE: "M122",

	GET_TACHOMETER_VALUE: "M123",

	IMMEDIATE_MOTOR_STOP: "M124",

	EXTRUDER_PRESSURE_PWM: "M128",
	EXTRUDER_PRESSURE_OFF: "M129",

	SET_PID_P_VALUE: "M130",
	SET_PID_I_VALUE: "M131",
	SET_PID_D_VALUE: "M132",
	SET_PID_I_LIMIT_VALUE: "M133",
	WRITE_PID_TO_EEPEOM: "M134",
	SET_PID_SAMPLE_INTERVAL: "M135",
	GET_PID_SETTINGS: "M136",

	SET_BED_TEMPERATURE_FAST: "M140",
	SET_CHAMBER_TEMPERATURE_FAST: "M141",

	HOLDING_RESSURE: "M142",

	MAXIMUM_HEATER_TEMPERATURE: "M143",

	BED_STANDBY: "M144"
};
